trigger:
  branches:
    include:
      - main
  paths:
    include:
      - rating-service/*

variables:
  DOCKER_REGISTRY: 'surendraprajapati'
  IMAGE_NAME: 'rating-service'
  PYTHON_VERSION: '3.11'

stages:

# Stage 1: Checkout
- stage: Checkout
  displayName: 'Checkout Code'
  jobs:
    - job: Checkout
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self

# Stage 2: Install Python Dependencies
- stage: PythonInstall
  displayName: 'Install Python Dependencies'
  dependsOn: Checkout
  jobs:
    - job: PythonInstall
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(PYTHON_VERSION)'
        - script: |
            cd rating-service
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi
          displayName: 'Install Python dependencies'

# Stage 3: Docker Build
- stage: DockerBuild
  displayName: 'Build & Push Docker Image'
  dependsOn: PythonInstall
  jobs:
    - job: Docker
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker-connection'
            command: 'login'

        - task: Docker@2
          inputs:
            repository: '$(DOCKER_REGISTRY)/$(IMAGE_NAME)'
            command: 'build'
            Dockerfile: 'rating-service/Dockerfile'
            tags: '$(Build.BuildId)'

        - task: Docker@2
          inputs:
            containerRegistry: 'docker-connection'
            repository: '$(DOCKER_REGISTRY)/$(IMAGE_NAME)'
            command: 'push'
            tags: '$(Build.BuildId)'

# Stage 4: Trivy Scan
- stage: TrivyScan
  displayName: 'Scan Docker Image with Trivy'
  dependsOn: DockerBuild
  jobs:
    - job: Trivy
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - script: |
            echo "Installing Trivy..."
            sudo apt-get update
            sudo apt-get install -y wget gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
            echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install -y trivy

        - script: |
            echo "Running Trivy scan..."
            docker pull $(DOCKER_REGISTRY)/$(IMAGE_NAME):$(Build.BuildId)
            trivy image --format table --output rating-service-image-scan.html $(DOCKER_REGISTRY)/$(IMAGE_NAME):$(Build.BuildId)
          displayName: 'Trivy Docker Image Scan'

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: 'rating-service-image-scan.html'
            artifact: 'trivy-report'
            publishLocation: 'pipeline'

# Stage 5: Update Docker Image Tag in Manifests
- stage: UpdateManifest
  displayName: 'Update Docker Image Tag in Kubernetes Manifests'
  dependsOn: TrivyScan
  variables:
    - group: ado-token
  jobs:
    - job: UpdateManifest
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - script: |
            echo "Updating manifest..."
            cd "$(Build.SourcesDirectory)"
            SERVICE_NAME="rating-service"
            REGISTRY="$(DOCKER_REGISTRY)"
            NEW_TAG="$(Build.BuildId)"
            bash update-manifest.sh "$SERVICE_NAME" "$REGISTRY" "$NEW_TAG"
          displayName: 'Run manifest update script'
          env:
            AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)

        - task: PublishPipelineArtifact@1
          displayName: 'Publish updated Kubernetes manifests'
          inputs:
            targetPath: '$(Build.SourcesDirectory)/k8s/rating-service-deployment.yaml'
            artifact: 'rating-service-manifest'
            publishLocation: 'pipeline'
